import { streamText, generateText } from "ai";
import { createGoogleGenerativeAI } from "@ai-sdk/google";
import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();
const google = createGoogleGenerativeAI({ apiKey: process.env.GEMINI_API_KEY });

export async function GET(req: Request, { params }: { params: Promise<{ id: string }> }) {
  try {
    const resolvedParams = await params;
    const messages = await prisma.chatMessage.findMany({
      where: { reportId: resolvedParams.id },
      orderBy: { createdAt: "asc" }
    });
    return Response.json(messages.map(m => ({
      id: m.id,
      role: m.role,
      content: m.content
    })));
  } catch (error) {
    return Response.json({ error: "Failed to fetch messages" }, { status: 500 });
  }
}

export async function POST(req: Request, { params }: { params: Promise<{ id: string }> }) {
  const { messages } = await req.json();
  const resolvedParams = await params;
  const reportId = resolvedParams.id;

  // 1. Fetch Report & Intelligence
  const report = await prisma.report.findUnique({
    where: { id: reportId },
    include: { company: true }
  });

  if (!report) {
    return Response.json({ error: "Report not found" }, { status: 404 });
  }

  const latestUserMessage = messages[messages.length - 1];

  // 2. Save user message to DB
  await prisma.chatMessage.create({
    data: {
      reportId: reportId,
      role: "user",
      content: latestUserMessage.content
    }
  });

  // 3. Construct System Prompt using the generated intelligence
  const companyName = report.company?.name || "the company";
  const insightsStr = JSON.stringify(report.insights || {}, null, 2);
  const deltaStr = JSON.stringify(report.deltaInsights || {}, null, 2);

  const systemPrompt = `You are ArthAI, an elite intelligence assistant. You are currently chatting with the lead about their personalized intelligence report.
The lead's company is: ${companyName}.
Here is the core intelligence generated by the pipeline:
${insightsStr}

Here are delta signals (changes since last audit, if any):
${deltaStr}

Rules:
1. Be exceptionally helpful, concise, and strategic.
2. Format your response clearly using markdown, bullet points, and short paragraphs.
3. Draw directly from the intelligence provided. If the lead asks a question you don't know the answer to, deduce it intelligently based on the context or admit what data is missing.
4. If they ask about competitors, digital readiness, or visual intelligence, reference those specific blocks from the report context.
5. Emphasize actionable next steps to drive revenue and value compounding.`;

  // 4. Generate & Stream Response
  const result = await streamText({
    model: google("gemini-2.0-flash"),
    system: systemPrompt,
    messages: messages,
    onFinish: async ({ text }) => {
      // 5. Save assistant message to DB after stream finishes
      await prisma.chatMessage.create({
        data: {
          reportId: reportId,
          role: "assistant",
          content: text
        }
      });
    }
  });

  return result.toTextStreamResponse();
}
